adding pairing request
adding pairing request to the application onCreate. This request will
get ignored by the reqpective other app, as the signature is not right
yet. You have to check logcat with the other app to see the actual
signature which is different than the expected signature:
java.lang.SecurityException: Signature F6/t7Bj0qtPDmfNdjqReSIHxR6lrwNxaHtT5go6f7HI= can't be verified for package com.mycelium.demo.world.